### ISSUE TITLE
ZGW Consumers must be updated in all projects

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-api-framework#66]
### Thema / Theme

API

### Omschrijving / Description

There are breaking changes but we need to bite the bullet or risk getting behind too much. My suggestion is to start with the simplest component to update and see the backlash from it. We can then report the backlash in the refinement.

* [x] Open Zaak (@stevenbal  ) https://github.com/open-zaak/open-zaak/pull/1800
* [x] Open Notifications (@SonnyBA ) https://github.com/open-zaak/open-notificaties/pull/196
* [x] Objects API (@annashamray ) https://github.com/maykinmedia/objects-api/pull/478
* [x] Objecttypes API (@annashamray ) - https://github.com/maykinmedia/objecttypes-api/pull/134
* [ ] Open Klant (@SonnyBA ) https://github.com/maykinmedia/open-klant/pull/278
* [x] Referentielijsten API (@annashamray ) https://github.com/maykinmedia/referentielijsten/pull/33

**Comment by SonnyBA** [comment]
@annashamray / @stevenbal, now that `commonground-api-common` has version `2.0.1` ([and requires](https://github.com/maykinmedia/open-api-framework/blob/main/pyproject.toml#L44) `zgw-consumers>=0.35.1`). I think `open-api-framework` also should be version bumped and pinned to the earlier mentioned `commground-api-common` version? This way projects won't have to pin `commground-api-common` as that should be done through `open-api-framework` (which from the looks of it can drop the `zgw-consumers` requirement, because `commonground-api-common` pulls that in).

The projects should also pin this new version `open-api-framework` version (and remove the redundant `commonground-api-common` requirement in the requirements file).

**Comment by SonnyBA** [comment]
> @SonnyBA pinning `commonground-api-commmon` in the OAF is a nice idea! This way you won't have mismatched OAF and commongground-api-common in the projects. We can start doing it, but I don't think it's critical for the PRs linked to this issue @stevenbal what do you think?

OAF [pins](https://github.com/maykinmedia/open-api-framework/blob/main/pyproject.toml#L44) `commonground-api-common`, so I think we'll have to version bump in order to prevent mismatching `zgw-consumers` (which is pinned through `commonground-api-common`, [link](https://github.com/maykinmedia/commonground-api-common/blob/2.0.1/setup.cfg#L47), and [OAF itself](https://github.com/maykinmedia/open-api-framework/blob/main/pyproject.toml#L46)).

**Comment by stevenbal** [comment]
> I think open-api-framework also should be version bumped and pinned to the earlier mentioned commground-api-common version?

I agree

> We can start doing it, but I don't think it's critical for the PRs linked to this issue

let's indeed not make it blocking for these PRs
